-- Traffic Safety Management database schema
-- Postgres-compatible DDL for core domain tables
-- Core reference tables ----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(80),
    last_name VARCHAR(80),
    role VARCHAR(32) NOT NULL CHECK (role IN ('admin', 'manager', 'analyst', 'viewer')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_users_role ON users (role);
CREATE INDEX IF NOT EXISTS ix_users_is_active ON users (is_active);
CREATE INDEX IF NOT EXISTS ix_users_last_login_at ON users (last_login_at DESC);

CREATE TABLE IF NOT EXISTS intersections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50),
    control_type VARCHAR(32) NOT NULL CHECK (control_type IN ('traffic_light', 'priority', 'signalled', 'roundabout')),
    number_of_legs SMALLINT NOT NULL CHECK (number_of_legs > 0),
    has_cameras BOOLEAN NOT NULL DEFAULT FALSE,
    aadt INTEGER NOT NULL CHECK (aadt >= 0),
    spf_model_reference VARCHAR(255) NOT NULL,
    geo_location TEXT NOT NULL,
    city VARCHAR(120),
    street VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS road_segments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50),
    length_km NUMERIC(8,3) NOT NULL CHECK (length_km >= 0),
    lane_count SMALLINT NOT NULL CHECK (lane_count > 0),
    functional_class VARCHAR(20) NOT NULL CHECK (functional_class IN ('urban', 'rural', 'highway')),
    speed_limit_kmh SMALLINT NOT NULL CHECK (speed_limit_kmh > 0),
    aadt INTEGER NOT NULL CHECK (aadt >= 0),
    geo_location TEXT NOT NULL,
    city VARCHAR(120),
    street VARCHAR(120)
);

-- Accidents table ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS accidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL,
    location TEXT NOT NULL,
    severity VARCHAR(16),
    type VARCHAR(16) NOT NULL CHECK (type IN ('PDO', 'Injury')),
    cost NUMERIC(14,2) NOT NULL CHECK (cost >= 0),
    road_segment_id INTEGER REFERENCES road_segments(id) ON DELETE SET NULL,
    intersection_id INTEGER REFERENCES intersections(id) ON DELETE SET NULL,
    collision_type VARCHAR(32),
    cause_factor VARCHAR(32),
    weather_conditions VARCHAR(32),
    road_conditions VARCHAR(32),
    visibility_conditions VARCHAR(32),
    injured_persons_count INTEGER NOT NULL DEFAULT 0 CHECK (injured_persons_count >= 0),
    location_description TEXT,
    distance_from_start NUMERIC(10,3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accidents_location_check CHECK (
        (road_segment_id IS NOT NULL AND intersection_id IS NULL)
        OR (road_segment_id IS NULL AND intersection_id IS NOT NULL)
    ),
    CONSTRAINT accidents_severity_chk CHECK (
        severity IS NULL OR severity IN ('minor', 'serious', 'severe', 'fatal')
    ),
    CONSTRAINT accidents_collision_type_chk CHECK (
        collision_type IS NULL OR collision_type IN ('rear_end', 'side', 'head_on', 'sideswipe', 'single_vehicle', 'angle', 'other')
    ),
    CONSTRAINT accidents_cause_factor_chk CHECK (
        cause_factor IS NULL OR cause_factor IN (
            'speeding', 'distracted_driving', 'alcohol', 'red_light_violation',
            'stop_sign_violation', 'improper_lane_change', 'following_too_close',
            'vehicle_failure', 'road_conditions', 'weather', 'other'
        )
    ),
    CONSTRAINT accidents_weather_chk CHECK (
        weather_conditions IS NULL OR weather_conditions IN ('clear', 'cloudy', 'rain', 'heavy_rain', 'snow', 'ice', 'fog', 'wind', 'other')
    ),
    CONSTRAINT accidents_road_cond_chk CHECK (
        road_conditions IS NULL OR road_conditions IN ('dry', 'wet', 'snow_covered', 'ice_covered', 'slush', 'loose_gravel', 'potholes', 'construction', 'other')
    ),
    CONSTRAINT accidents_visibility_chk CHECK (
        visibility_conditions IS NULL OR visibility_conditions IN ('excellent', 'good', 'fair', 'poor', 'very_poor', 'night', 'dawn', 'dusk', 'other')
    )
);

CREATE INDEX IF NOT EXISTS ix_accidents_occurred_at ON accidents (occurred_at);
CREATE INDEX IF NOT EXISTS ix_accidents_type ON accidents (type);
CREATE INDEX IF NOT EXISTS ix_accidents_severity ON accidents (severity);
CREATE INDEX IF NOT EXISTS ix_accidents_road_segment ON accidents (road_segment_id);
CREATE INDEX IF NOT EXISTS ix_accidents_intersection ON accidents (intersection_id);
CREATE INDEX IF NOT EXISTS ix_accidents_collision_type ON accidents (collision_type);
CREATE INDEX IF NOT EXISTS ix_accidents_cause_factor ON accidents (cause_factor);

-- Hotspots table -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS hotspots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    road_segment_id INTEGER REFERENCES road_segments(id) ON DELETE SET NULL,
    intersection_id INTEGER REFERENCES intersections(id) ON DELETE SET NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL CHECK (period_end >= period_start),
    observed_crashes JSONB NOT NULL DEFAULT CAST('{}' AS JSONB),
    expected_crashes NUMERIC(12,4) NOT NULL CHECK (expected_crashes >= 0),
    risk_score NUMERIC(12,4) NOT NULL CHECK (risk_score >= 0),
    status VARCHAR(32) NOT NULL CHECK (status IN ('open', 'reviewed', 'addressed')),
    screening_parameters JSONB,
    CONSTRAINT hotspots_location_check CHECK (
        (road_segment_id IS NOT NULL AND intersection_id IS NULL)
        OR (road_segment_id IS NULL AND intersection_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_hotspots_road_segment ON hotspots (road_segment_id);
CREATE INDEX IF NOT EXISTS ix_hotspots_intersection ON hotspots (intersection_id);
CREATE INDEX IF NOT EXISTS ix_hotspots_status ON hotspots (status);
CREATE INDEX IF NOT EXISTS ix_hotspots_risk_score ON hotspots (risk_score DESC);

-- Countermeasures table ----------------------------------------------------
CREATE TABLE IF NOT EXISTS countermeasures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    target_type VARCHAR(32) NOT NULL CHECK (target_type IN ('RoadSegment', 'Intersection')),
    applicability_rules JSONB NOT NULL DEFAULT CAST('{}' AS JSONB),
    affected_collision_types JSONB NOT NULL DEFAULT CAST('[]' AS JSONB),
    affected_severities JSONB NOT NULL DEFAULT CAST('[]' AS JSONB),
    cmf NUMERIC(10,4) NOT NULL CHECK (cmf > 0),
    lifecycle_status VARCHAR(32) NOT NULL CHECK (lifecycle_status IN ('proposed', 'approved', 'implemented')),
    implementation_cost_amount NUMERIC(14,2) NOT NULL CHECK (implementation_cost_amount >= 0),
    implementation_cost_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    expected_annual_savings NUMERIC(14,2),
    evidence TEXT,
    CONSTRAINT countermeasures_expected_savings_chk CHECK (
        expected_annual_savings IS NULL OR expected_annual_savings >= 0
    )
);

CREATE INDEX IF NOT EXISTS ix_countermeasures_target_type ON countermeasures (target_type);
CREATE INDEX IF NOT EXISTS ix_countermeasures_lifecycle_status ON countermeasures (lifecycle_status);

-- Projects table -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    countermeasure_id INTEGER NOT NULL REFERENCES countermeasures(id) ON DELETE CASCADE,
    hotspot_id INTEGER NOT NULL REFERENCES hotspots(id) ON DELETE CASCADE,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL CHECK (period_end >= period_start),
    expected_cost_amount NUMERIC(14,2) NOT NULL CHECK (expected_cost_amount >= 0),
    expected_cost_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    actual_cost_amount NUMERIC(14,2),
    actual_cost_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    status VARCHAR(32) NOT NULL CHECK (status IN ('proposed', 'approved', 'implemented', 'closed')),
    CONSTRAINT projects_actual_cost_chk CHECK (
        actual_cost_amount IS NULL OR actual_cost_amount >= 0
    )
);

CREATE INDEX IF NOT EXISTS ix_projects_countermeasure ON projects (countermeasure_id);
CREATE INDEX IF NOT EXISTS ix_projects_hotspot ON projects (hotspot_id);
CREATE INDEX IF NOT EXISTS ix_projects_status ON projects (status);
